name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: setting an error message
        run: echo "::error::Missing semicolon"
      - name: setting an error message with params
        run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
      - name: setting a debug message with params
        run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
      - name: setting a warning message with params
        run: echo "::warning title=Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
      - name: setting a notice message with params
        run: echo "::notice title=Notice title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
      - name: group of logs
        run: |
          echo "::group::My group title"
          echo "inside group"
          echo "::endgroup::"
      - name: masking a value
        run: echo "::add-mask""Secret String"
      - name: echo a secret
        run: echo "Secret String"
